version: '3.1'

services:
    app:
        env_file: .env
        build:
            context: .
            dockerfile: ./Containerfile
        volumes:
            # [CR]: k čemu tu jsou volumes? Potřebujeme vidět zkompilovaný kód?
            - type: bind
              source: ./src
              target: /app/src
        ports:
            - '3000:3000'
